### ISSUE TITLE
WOW ID format has changed

### ISSUE THREAD

**Issue by n3m0x** [ekkelenkamp/netatmo2wow#1]
Hi. 

Because the ID format of the MetOffice WOW Station ID has changed in Mai 2016 it is not possible to use the new WOW Station ID in netatmo2wow anymore. 

ID example for pre-June 2016 sites (956916003) ID example for current sites (6a571450-df53-e611-9401-0003ff5987fd) 

See: http://wow.metoffice.gov.uk/support/dataformats#dataAWS  

Can you please update netatmo2wow to the new MetOffice WOW Station ID format. 
Thank you.

**Comment by ekkelenkamp** [comment]
Since the siteId is handled as a string in the netatmo2wow tool, the changed format shouldn't be an issue. Could you show a log of any problems you have with the upload?

**Comment by n3m0x** [comment]
Hi,

Thank you for your fast response. I think it is a general problem on my
side.

I do run netatmo2wow in Windows:

java -jar netatmo2wow-2.0.jar
    -clientid <5a0dfa7db05a21c334c34c346>
    -secret <7sJQAqCHVhkfll2mSLmu0kCirlGAkM>
    -email <abc@xyz.com>
    -password <abcdef>
    -timeperiod <600>
    -siteid <a1234567890-cde2-ee22-0001-00aabb00>
    -awspin <1234567>

and do get:

java -jar netatmo2wow-2.0.jar
java.lang.NullPointerException
        at java.net.URLEncoder.encode(Unknown Source)
        at
com.ekkelenkamp.netatmo2wow.NetatmoHttpClientImpl.createParamsLine(NetatmoHttpClientImpl.java:139)
        at
com.ekkelenkamp.netatmo2wow.NetatmoHttpClientImpl.applyParams(NetatmoHttpClientImpl.java:116)
        at
com.ekkelenkamp.netatmo2wow.NetatmoHttpClientImpl.post(NetatmoHttpClientImpl.java:70)
        at
com.ekkelenkamp.netatmo2wow.NetatmoDownload.login(NetatmoDownload.java:215)
        at
com.ekkelenkamp.netatmo2wow.NetatmoDownload.downloadMeasures(NetatmoDownload.java:33)
        at com.ekkelenkamp.netatmo2wow.Cli.run(Cli.java:93)
        at com.ekkelenkamp.netatmo2wow.Cli.parse(Cli.java:65)
        at com.ekkelenkamp.netatmo2wow.Main.main(Main.java:8)
Exception in thread "main" java.lang.RuntimeException:
java.lang.NumberFormatException: null
        at com.ekkelenkamp.netatmo2wow.Cli.run(Cli.java:106)
        at com.ekkelenkamp.netatmo2wow.Cli.parse(Cli.java:65)
        at com.ekkelenkamp.netatmo2wow.Main.main(Main.java:8)
Caused by: java.lang.NumberFormatException: null
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at
com.ekkelenkamp.netatmo2wow.NetatmoDownload.downloadMeasures(NetatmoDownload.java:36)
        at com.ekkelenkamp.netatmo2wow.Cli.run(Cli.java:93)
        ... 2 more

Greetings,
Andreas


2017-12-01 16:17 GMT+01:00 Rudie Ekkelenkamp <notifications@github.com>:

**Comment by flappah** [comment]
There are a few issues with the regular build for which I made a few corrections a while ago for example support for the windmeter but also a fix for the issue you mentioned. I’m using this in a private build. I’m not quite sure it’s 100% bug free but it’s already running without issues for a few months. I was trying to check this build in this week on my private branch but got “bitten by the flue bug”. I’ll do my best to check it in this weekend.

**Comment by ekkelenkamp** [comment]
Hi,

I never got the change to change to test for a windmeter since I don't own one. it would be greate if you could make a pull request so the wind meter is supported as well!

**Comment by ekkelenkamp** [comment]
Just made a fix that resolves the NullPointerException issue. I release version 2.1. Hope this solves your issue.

**Comment by flappah** [comment]
Sure! No problem. I’ll do that next week and version wise it makes sense. Currently I’ve made it version 2.24. I’ll make the pull request this week when I’m feeling a bit better again!
