### ISSUE TITLE
0 data values for most properties

### ISSUE THREAD

**Issue by markavey** [ekkelenkamp/netatmo2wow#2]
Hi,

I'm just setting this up now on my Synology NAS. I managed to get an initial send to WOW, but most data values are set to 0.

Here's some sample output from the script:

tempf=32&dateutc=2017-12-04+12%3A27%3A07&baromin=30.47&humidity=0.0

As you can see, only baromin is correct here (32 being 0 for the temp) and all values apart from Baro are 0 on the Met Office site.

I'm using netatmo2wow-2.1.jar.

Any ideas?

Regards,

Mark

**Comment by flappah** [comment]
I'm using a modified version of netatmo2wow and ran into this issue a while ago. It's all got to do with Netatmo's wind gauge. I assume you have one yourself as well. If this is the case you could try my jar file. I still need to patch my changes into the official build but am still coping with the effects of a flu infection. 
[netatmo2wow-2.24.zip](https://github.com/ekkelenkamp/netatmo2wow/files/1531139/netatmo2wow-2.24.zip)

**Comment by markavey** [comment]
Hi Richard,

Many thanks for the prompt reply.

I do indeed have the wind gauge (and rain gauge). I shall try your jar
file when I get home.
Hope you’re feeling better soon 😄 

Regards,

Mark


On Tue, 5 Dec 2017, at 12:45 PM, Richard Flapper wrote:
> I'm using a modified version of netatmo2wow and ran into this issue a
> while ago. It's all got to do with Netatmo's wind gauge. I assume you
> have one yourself as well. If this is the case you could try my jar
> file. I still need to patch my changes into the official build but am
> still coping with the effects of a flu infection.> netatmo2wow-2.24.zip[1]


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 


http://www.markavey.com
You can send me encrypted email using Protonmail @
mark.avey@protonmail.com

Links:

  1. https://github.com/ekkelenkamp/netatmo2wow/files/1531139/netatmo2wow-2.24.zip
  2. https://github.com/ekkelenkamp/netatmo2wow/issues/2#issuecomment-349293836

**Comment by ekkelenkamp** [comment]
I just merged the changed of @flappah into the 2.2 release. You should be able to use this release.

**Comment by markavey** [comment]
Many thanks - working a treat now. Now I just need to work out how to automate the running of this script on my Synology :)

**Comment by ekkelenkamp** [comment]
You can take a look at the README. You can schedule it using a cron job. 
Thanks to Richard for providing the pull request!

**Comment by markavey** [comment]
Yep, sorry, should've mentioned I'd read it but wasn't familiar with adding a new CRON job to a Synology NAS. Some Googling and I think I'm sorted now.
